#!/usr/bin/env node
/**
 * DSYS-6 icon codegen. Reads the curated subset in tools/icons/subset.json, pulls each icon's
 * regular- and duotone-weight source SVG straight out of @phosphor-icons/core's raw asset
 * files, and emits a single generated TS module exporting:
 *
 *   - IconName: a typed union of every icon in the subset (no consuming code can reference an
 *     icon that doesn't exist -- a compile error instead of a silently-missing glyph).
 *   - IconWeight: 'regular' | 'duotone'.
 *   - ICON_REGISTRY: IconName -> weight -> inner SVG markup (just the <path> elements; the
 *     <ums-icon> component supplies its own <svg> wrapper with the real accessibility/sizing
 *     attributes -- see icon.component.ts).
 *
 * This is the DSYS-6 "no inline <svg> in feature code" mechanism: a consuming app writes
 * `<ums-icon name="graduation-cap" />`, never a hand-copied SVG path.
 */
import { readFile, writeFile, mkdir } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';
const __dirname = dirname(fileURLToPath(import.meta.url));
const repoRoot = join(__dirname, '..', '..');
const outDir = join(repoRoot, 'projects/design-system/src/lib/icon');
const assetsDir = join(repoRoot, 'node_modules/@phosphor-icons/core/assets');

const subset = JSON.parse(await readFile(join(__dirname, 'subset.json'), 'utf-8'));

/** Strip the outer <svg ...>...</svg> wrapper, keeping only the inner markup. */
function extractInnerMarkup(svgSource) {
  const match = svgSource.match(/<svg[^>]*>([\s\S]*)<\/svg>/);
  if (!match) {
    throw new Error(`Could not parse an <svg> root element out of:\n${svgSource}`);
  }
  return match[1].trim();
}

async function readIconMarkup(weight, iconName) {
  const fileName = weight === 'regular' ? `${iconName}.svg` : `${iconName}-${weight}.svg`;
  const filePath = join(assetsDir, weight, fileName);
  let source;
  try {
    source = await readFile(filePath, 'utf-8');
  } catch {
    throw new Error(
      `Icon "${iconName}" (${weight}) is listed in tools/icons/subset.json but ` +
        `${filePath} does not exist in the installed @phosphor-icons/core package. Check the ` +
        'spelling against https://phosphoricons.com, or remove it from the subset.',
    );
  }
  return extractInnerMarkup(source);
}

const iconNames = [...subset.icons].sort();
const registryEntries = [];

for (const iconName of iconNames) {
  const weights = {};
  for (const weight of subset.weights) {
    weights[weight] = await readIconMarkup(weight, iconName);
  }
  registryEntries.push([iconName, weights]);
}

const iconNameUnion = iconNames.map((name) => `  | '${name}'`).join('\n');
const weightUnion = subset.weights.map((w) => `'${w}'`).join(' | ');

const registryLiteral = registryEntries
  .map(([name, weights]) => {
    const weightLines = Object.entries(weights)
      .map(([weight, markup]) => `    ${weight}: ${JSON.stringify(markup)},`)
      .join('\n');
    return `  '${name}': {\n${weightLines}\n  },`;
  })
  .join('\n');

const output = `/**
 * Do not edit directly -- generated by tools/icons/build-icons.mjs from tools/icons/subset.json
 * and the raw SVGs in the installed @phosphor-icons/core package. Regenerate with
 * \`npm run icons:build\` after editing the subset.
 */

/* eslint-disable @typescript-eslint/naming-convention -- generated from icon file names */

/** requirement-spec.md §10 item 2: "a typed IconName union generated from the actual set in use." */
export type IconName =
${iconNameUnion};

export type IconWeight = ${weightUnion};

export const ICON_NAMES: readonly IconName[] = ${JSON.stringify(iconNames)} as const;

/** Inner SVG markup (viewBox is always "0 0 256 256" -- Phosphor's fixed grid) per icon per weight. */
export const ICON_REGISTRY: Record<IconName, Record<IconWeight, string>> = {
${registryLiteral}
};
`;

await mkdir(outDir, { recursive: true });
await writeFile(join(outDir, 'icon-registry.generated.ts'), output, 'utf-8');

console.log(
  `icons\n✔︎ ${iconNames.length} icons x ${subset.weights.length} weights -> ${join(outDir, 'icon-registry.generated.ts')}`,
);
