#!/usr/bin/env node
/**
 * DSYS-1 token build pipeline.
 *
 * One source of truth -- the JSON files under tools/tokens/source/ -- produces three build
 * outputs (requirement-spec.md §9: "CSS custom properties, SCSS variables, and a typed
 * TypeScript token map... from one source, so tokens and components never drift out of sync"):
 *
 *   1. projects/design-system/src/lib/styles/tokens.css   -- CSS custom properties
 *   2. projects/design-system/src/lib/styles/_tokens.scss -- SCSS variables (compile-time only)
 *   3. projects/design-system/src/lib/tokens/tokens.generated.ts -- typed TS token map
 *
 * Layering (requirement-spec.md §7, design-decisions.md "Theming"): tokens under the
 * "primitive" branch of the source tree are raw brand constants, never emitted to any output --
 * only "semantic" tokens (color.*, type.*, space.*, radius.*, shadow.*, motion.*, bp.*, font.*)
 * are public. A semantic token's `value` (and optional `dark`/`operational` sibling) may
 * *reference* a primitive (e.g. "{primitive.color.navy-700}"); Style Dictionary resolves that
 * reference on every field, not just `value`, before this script ever runs its own formatters.
 *
 * Dark theme (edge-cases.md, design-decisions.md "Theme-Switch Transition Mechanism"): a token
 * with a `dark` field gets a light default on :root, then a dark override both under
 * `@media (prefers-color-scheme: dark)` (system mode) and under `[data-theme="dark"]` (explicit
 * override) -- see ThemeService in projects/design-system/src/lib/theming.
 *
 * Two-intensity typography register (requirement-spec.md §2 Principle #4): a token with an
 * `operational` field gets that value under `[data-register="operational"]`, which
 * ums-admin-web/ums-faculty-web set on their app root.
 *
 * Deprecated aliases (design-decisions.md "Token Versioning & Deprecation Policy"): entries in
 * tools/tokens/deprecated-aliases.json are emitted as extra CSS custom properties that still
 * resolve to the current token's value, for one full major-version cycle after a rename.
 */
import { readFile, mkdir } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';
import StyleDictionary from 'style-dictionary';

const __dirname = dirname(fileURLToPath(import.meta.url));
const repoRoot = join(__dirname, '..', '..');
const cssOutDir = join(repoRoot, 'projects/design-system/src/lib/styles');
const tsOutDir = join(repoRoot, 'projects/design-system/src/lib/tokens');

const deprecatedAliases = JSON.parse(
  await readFile(join(__dirname, 'deprecated-aliases.json'), 'utf-8'),
).aliases;

/** Only semantic tokens are ever emitted -- primitives stay internal to the source tree. */
const isPublicToken = (token) => !token.path.includes('primitive');

const toCamel = (segment) => segment.replace(/-([a-z0-9])/g, (_, c) => c.toUpperCase());

const cssComment = (token) => (token.comment ? ` /* ${token.comment} */` : '');

/** Resolve a deprecated-alias entry's dot path ("color.primary") to its built token. */
function resolveAliasTarget(dotPath, allTokens) {
  const name = dotPath.split('.').join('-');
  const token = allTokens.find((t) => t.name === name);
  if (!token) {
    throw new Error(
      `deprecated-aliases.json points at "${dotPath}", which does not match any built token (expected name "${name}"). Fix the alias entry or the token path.`,
    );
  }
  return token;
}

StyleDictionary.registerFormat({
  name: 'ums/css',
  format: async ({ dictionary }) => {
    const tokens = dictionary.allTokens.filter(isPublicToken);
    const light = [];
    const dark = [];
    const operational = [];

    for (const token of tokens) {
      const varName = `--${token.name}`;
      light.push(`  ${varName}: ${token.value};${cssComment(token)}`);
      if (token.dark !== undefined) dark.push(`  ${varName}: ${token.dark};`);
      if (token.operational !== undefined) operational.push(`  ${varName}: ${token.operational};`);
    }

    const aliasLines = deprecatedAliases.map(({ oldName, tokenPath }) => {
      const target = resolveAliasTarget(tokenPath, tokens);
      return `  ${oldName}: var(--${target.name}); /* deprecated alias for --${target.name}, retire after the next major */`;
    });

    return `/**
 * Do not edit directly -- generated by tools/tokens/build-tokens.mjs from tools/tokens/source/*.json.
 * requirement-spec.md §3-§5, §7. Regenerate with \`npm run tokens:build\`.
 */

:root {
${light.join('\n')}
}

/* System dark mode (requirement-spec.md §7 "system" theme mode) -- only applies while no
   explicit override is set via ThemeService (data-theme attribute). */
@media (prefers-color-scheme: dark) {
  :root:not([data-theme='light']) {
${dark.join('\n')}
  }
}

/* Explicit dark override (ThemeService sets data-theme="dark" on <html>), wins regardless of OS
   preference -- also what a screenshot-diffing test forces for the dark-theme catalog variant. */
:root[data-theme='dark'] {
${dark.join('\n')}
}

/* Two-intensity typography register (requirement-spec.md §2 Principle #4). ums-admin-web and
   ums-faculty-web set [data-register="operational"] on their app root. */
:root[data-register='operational'] {
${operational.join('\n')}
}
${
  aliasLines.length
    ? `\n/* Deprecated aliases -- design-decisions.md "Token Versioning & Deprecation Policy".
   Kept for one full major-version cycle after the rename that introduced them. */\n:root {\n${aliasLines.join('\n')}\n}\n`
    : ''
}`;
  },
});

StyleDictionary.registerFormat({
  name: 'ums/scss',
  format: async ({ dictionary }) => {
    const tokens = dictionary.allTokens.filter(isPublicToken);
    const lines = tokens.map((token) => `$${token.name}: ${token.value};${cssComment(token)}`);
    return `// Do not edit directly -- generated by tools/tokens/build-tokens.mjs.
// SCSS variables are a compile-time snapshot of the LIGHT theme, for build-time math only
// (e.g. \`$radius-md * 2\`, breakpoint mixins). They are NOT theme-reactive.
// Runtime, theme-aware styling must use the CSS custom property instead: var(--${tokens[0]?.name ?? 'token-name'}),
// never this SCSS variable, inside any component that needs to repaint on a theme switch.

${lines.join('\n')}
`;
  },
});

StyleDictionary.registerFormat({
  name: 'ums/ts',
  format: async ({ dictionary }) => {
    const tokens = dictionary.allTokens.filter(isPublicToken);

    // Build a nested plain-object tree of CSS var() reference strings, mirroring the source
    // JSON's own grouping, so this map can never drift out of step with the CSS/SCSS outputs --
    // consuming code imports Tokens.color.primary instead of writing var(--color-primary) by
    // hand (design-decisions.md "Token Versioning & Deprecation Policy" / the consumption
    // contract lint rule in eslint.config.js).
    const tree = {};
    const cssVarNames = [];
    for (const token of tokens) {
      cssVarNames.push(`--${token.name}`);
      let node = tree;
      const segments = token.path.map(toCamel);
      for (let i = 0; i < segments.length - 1; i++) {
        node = node[segments[i]] ??= {};
      }
      node[segments.at(-1)] = `var(--${token.name})`;
    }

    // Flat, typed light/dark literal-value map for the one class of consumer the CSS cascade
    // can't reach on its own: JS-computed color (canvas/SVG chart fills) -- design-decisions.md
    // "Theme-Switch Transition Mechanism (Mid-Interaction Safety)". A future chart wrapper
    // (DSYS-16) re-resolves these live via ThemeService.resolveCssVar() rather than trusting a
    // value snapshotted at build time; this map exists as the typed seed/fallback and for
    // generating a static theme object (e.g. an ECharts theme JSON) without a live DOM.
    const colorTokens = tokens.filter((t) => t.path[0] === 'color');
    const colorRawValues = {};
    for (const token of colorTokens) {
      colorRawValues[toCamel(token.path.at(-1))] = {
        light: token.value,
        dark: token.dark ?? token.value,
      };
    }

    const serialize = (value, indent) => {
      if (typeof value === 'string') return JSON.stringify(value);
      const pad = '  '.repeat(indent);
      const innerPad = '  '.repeat(indent + 1);
      if (Array.isArray(value)) {
        const items = value.map((val) => `${innerPad}${serialize(val, indent + 1)},`);
        return `[\n${items.join('\n')}\n${pad}]`;
      }
      const entries = Object.entries(value).map(
        ([key, val]) =>
          `${innerPad}${/^[A-Za-z_$][\w$]*$/.test(key) ? key : JSON.stringify(key)}: ${serialize(val, indent + 1)},`,
      );
      return `{\n${entries.join('\n')}\n${pad}}`;
    };

    return `/**
 * Do not edit directly -- generated by tools/tokens/build-tokens.mjs from tools/tokens/source/*.json.
 * requirement-spec.md §9: "a typed TypeScript token map... from one source, so tokens and
 * components never drift out of sync." Regenerate with \`npm run tokens:build\`.
 *
 * Consume Tokens.* (and, for JS-computed color only, ColorTokenValues.*) instead of a raw
 * \`var(--...)\` string literal -- the design system's own ESLint rule
 * (ums/no-raw-design-token-css-var) fails a build that does the latter outside this package's
 * own token source.
 */

/* eslint-disable @typescript-eslint/naming-convention -- generated from the token source tree */

export const Tokens = ${serialize(tree, 0)} as const;

export type TokenTree = typeof Tokens;

/** Every CSS custom property this package defines, for tooling (lint rules, alias checks). */
export const ALL_DESIGN_TOKEN_CSS_VARS = ${serialize(cssVarNames, 0)} as const;

export type DesignTokenCssVar = (typeof ALL_DESIGN_TOKEN_CSS_VARS)[number];

/**
 * Literal light/dark hex values per semantic color token, for JS-computed-color contexts only
 * (canvas/SVG chart fills -- see the class doc above). Everything else should read \`Tokens.color.*\`.
 */
export const ColorTokenValues = ${serialize(colorRawValues, 0)} as const;

export type ColorTokenName = keyof typeof ColorTokenValues;
`;
  },
});

const sd = new StyleDictionary({
  source: [join(__dirname, 'source/**/*.json')],
  platforms: {
    css: {
      transforms: ['attribute/cti', 'name/kebab'],
      buildPath: `${cssOutDir}/`,
      files: [{ destination: 'tokens.css', format: 'ums/css' }],
    },
    scss: {
      transforms: ['attribute/cti', 'name/kebab'],
      buildPath: `${cssOutDir}/`,
      files: [{ destination: '_tokens.scss', format: 'ums/scss' }],
    },
    ts: {
      transforms: ['attribute/cti', 'name/kebab'],
      buildPath: `${tsOutDir}/`,
      files: [{ destination: 'tokens.generated.ts', format: 'ums/ts' }],
    },
  },
});

await mkdir(cssOutDir, { recursive: true });
await mkdir(tsOutDir, { recursive: true });
await sd.buildAllPlatforms();
