/**
 * Do not edit directly -- generated by tools/tokens/build-tokens.mjs from tools/tokens/source/*.json.
 * requirement-spec.md §9: "a typed TypeScript token map... from one source, so tokens and
 * components never drift out of sync." Regenerate with `npm run tokens:build`.
 *
 * Consume Tokens.* (and, for JS-computed color only, ColorTokenValues.*) instead of a raw
 * `var(--...)` string literal -- the design system's own ESLint rule
 * (ums/no-raw-design-token-css-var) fails a build that does the latter outside this package's
 * own token source.
 */

/* eslint-disable @typescript-eslint/naming-convention -- generated from the token source tree */

export const Tokens = {
  bp: {
    xs: "var(--bp-xs)",
    sm: "var(--bp-sm)",
    md: "var(--bp-md)",
    lg: "var(--bp-lg)",
    xl: "var(--bp-xl)",
    xxl: "var(--bp-xxl)",
  },
  color: {
    primary: "var(--color-primary)",
    primaryHover: "var(--color-primary-hover)",
    secondary: "var(--color-secondary)",
    accentText: "var(--color-accent-text)",
    success: "var(--color-success)",
    warning: "var(--color-warning)",
    danger: "var(--color-danger)",
    info: "var(--color-info)",
    background: "var(--color-background)",
    surface: "var(--color-surface)",
    surfaceAlt: "var(--color-surface-alt)",
    border: "var(--color-border)",
    text: "var(--color-text)",
    textMuted: "var(--color-text-muted)",
    disabled: "var(--color-disabled)",
    onPrimary: "var(--color-on-primary)",
    onSecondary: "var(--color-on-secondary)",
    onDanger: "var(--color-on-danger)",
    onSuccess: "var(--color-on-success)",
    onWarning: "var(--color-on-warning)",
    onInfo: "var(--color-on-info)",
  },
  shadow: {
    "0": "var(--shadow-0)",
    "1": "var(--shadow-1)",
    "2": "var(--shadow-2)",
    "3": "var(--shadow-3)",
    focus: "var(--shadow-focus)",
  },
  motion: {
    fast: "var(--motion-fast)",
    base: "var(--motion-base)",
    slow: "var(--motion-slow)",
    hero: "var(--motion-hero)",
    reduced: "var(--motion-reduced)",
  },
  ease: {
    standard: "var(--ease-standard)",
    emphasizedIn: "var(--ease-emphasized-in)",
    emphasizedOut: "var(--ease-emphasized-out)",
  },
  radius: {
    xs: "var(--radius-xs)",
    sm: "var(--radius-sm)",
    md: "var(--radius-md)",
    lg: "var(--radius-lg)",
    pill: "var(--radius-pill)",
    circle: "var(--radius-circle)",
  },
  space: {
    "1": "var(--space-1)",
    "2": "var(--space-2)",
    "3": "var(--space-3)",
    "4": "var(--space-4)",
    "5": "var(--space-5)",
    "6": "var(--space-6)",
    "7": "var(--space-7)",
    "8": "var(--space-8)",
    "9": "var(--space-9)",
  },
  font: {
    family: {
      display: "var(--font-family-display)",
      base: "var(--font-family-base)",
    },
    feature: {
      numeric: "var(--font-feature-numeric)",
    },
  },
  type: {
    display1: {
      fontSize: "var(--type-display-1-font-size)",
      lineHeight: "var(--type-display-1-line-height)",
      fontWeight: "var(--type-display-1-font-weight)",
      fontFamily: "var(--type-display-1-font-family)",
    },
    display2: {
      fontSize: "var(--type-display-2-font-size)",
      lineHeight: "var(--type-display-2-line-height)",
      fontWeight: "var(--type-display-2-font-weight)",
      fontFamily: "var(--type-display-2-font-family)",
    },
    heading1: {
      fontSize: "var(--type-heading-1-font-size)",
      lineHeight: "var(--type-heading-1-line-height)",
      fontWeight: "var(--type-heading-1-font-weight)",
      fontFamily: "var(--type-heading-1-font-family)",
    },
    heading2: {
      fontSize: "var(--type-heading-2-font-size)",
      lineHeight: "var(--type-heading-2-line-height)",
      fontWeight: "var(--type-heading-2-font-weight)",
      fontFamily: "var(--type-heading-2-font-family)",
    },
    heading3: {
      fontSize: "var(--type-heading-3-font-size)",
      lineHeight: "var(--type-heading-3-line-height)",
      fontWeight: "var(--type-heading-3-font-weight)",
      fontFamily: "var(--type-heading-3-font-family)",
    },
    heading4: {
      fontSize: "var(--type-heading-4-font-size)",
      lineHeight: "var(--type-heading-4-line-height)",
      fontWeight: "var(--type-heading-4-font-weight)",
      fontFamily: "var(--type-heading-4-font-family)",
    },
    bodyLg: {
      fontSize: "var(--type-body-lg-font-size)",
      lineHeight: "var(--type-body-lg-line-height)",
      fontWeight: "var(--type-body-lg-font-weight)",
      fontFamily: "var(--type-body-lg-font-family)",
    },
    body: {
      fontSize: "var(--type-body-font-size)",
      lineHeight: "var(--type-body-line-height)",
      fontWeight: "var(--type-body-font-weight)",
      fontFamily: "var(--type-body-font-family)",
    },
    bodySm: {
      fontSize: "var(--type-body-sm-font-size)",
      lineHeight: "var(--type-body-sm-line-height)",
      fontWeight: "var(--type-body-sm-font-weight)",
      fontFamily: "var(--type-body-sm-font-family)",
    },
    label: {
      fontSize: "var(--type-label-font-size)",
      lineHeight: "var(--type-label-line-height)",
      fontWeight: "var(--type-label-font-weight)",
      fontFamily: "var(--type-label-font-family)",
      letterSpacing: "var(--type-label-letter-spacing)",
      textTransform: "var(--type-label-text-transform)",
    },
  },
} as const;

export type TokenTree = typeof Tokens;

/** Every CSS custom property this package defines, for tooling (lint rules, alias checks). */
export const ALL_DESIGN_TOKEN_CSS_VARS = [
  "--bp-xs",
  "--bp-sm",
  "--bp-md",
  "--bp-lg",
  "--bp-xl",
  "--bp-xxl",
  "--color-primary",
  "--color-primary-hover",
  "--color-secondary",
  "--color-accent-text",
  "--color-success",
  "--color-warning",
  "--color-danger",
  "--color-info",
  "--color-background",
  "--color-surface",
  "--color-surface-alt",
  "--color-border",
  "--color-text",
  "--color-text-muted",
  "--color-disabled",
  "--color-on-primary",
  "--color-on-secondary",
  "--color-on-danger",
  "--color-on-success",
  "--color-on-warning",
  "--color-on-info",
  "--shadow-0",
  "--shadow-1",
  "--shadow-2",
  "--shadow-3",
  "--shadow-focus",
  "--motion-fast",
  "--motion-base",
  "--motion-slow",
  "--motion-hero",
  "--motion-reduced",
  "--ease-standard",
  "--ease-emphasized-in",
  "--ease-emphasized-out",
  "--radius-xs",
  "--radius-sm",
  "--radius-md",
  "--radius-lg",
  "--radius-pill",
  "--radius-circle",
  "--space-1",
  "--space-2",
  "--space-3",
  "--space-4",
  "--space-5",
  "--space-6",
  "--space-7",
  "--space-8",
  "--space-9",
  "--font-family-display",
  "--font-family-base",
  "--font-feature-numeric",
  "--type-display-1-font-size",
  "--type-display-1-line-height",
  "--type-display-1-font-weight",
  "--type-display-1-font-family",
  "--type-display-2-font-size",
  "--type-display-2-line-height",
  "--type-display-2-font-weight",
  "--type-display-2-font-family",
  "--type-heading-1-font-size",
  "--type-heading-1-line-height",
  "--type-heading-1-font-weight",
  "--type-heading-1-font-family",
  "--type-heading-2-font-size",
  "--type-heading-2-line-height",
  "--type-heading-2-font-weight",
  "--type-heading-2-font-family",
  "--type-heading-3-font-size",
  "--type-heading-3-line-height",
  "--type-heading-3-font-weight",
  "--type-heading-3-font-family",
  "--type-heading-4-font-size",
  "--type-heading-4-line-height",
  "--type-heading-4-font-weight",
  "--type-heading-4-font-family",
  "--type-body-lg-font-size",
  "--type-body-lg-line-height",
  "--type-body-lg-font-weight",
  "--type-body-lg-font-family",
  "--type-body-font-size",
  "--type-body-line-height",
  "--type-body-font-weight",
  "--type-body-font-family",
  "--type-body-sm-font-size",
  "--type-body-sm-line-height",
  "--type-body-sm-font-weight",
  "--type-body-sm-font-family",
  "--type-label-font-size",
  "--type-label-line-height",
  "--type-label-font-weight",
  "--type-label-font-family",
  "--type-label-letter-spacing",
  "--type-label-text-transform",
] as const;

export type DesignTokenCssVar = (typeof ALL_DESIGN_TOKEN_CSS_VARS)[number];

/**
 * Literal light/dark hex values per semantic color token, for JS-computed-color contexts only
 * (canvas/SVG chart fills -- see the class doc above). Everything else should read `Tokens.color.*`.
 */
export const ColorTokenValues = {
  primary: {
    light: "#1D3A6E",
    dark: "#7CA3DE",
  },
  primaryHover: {
    light: "#142A52",
    dark: "#9BBBEB",
  },
  secondary: {
    light: "#C9972E",
    dark: "#E4B450",
  },
  accentText: {
    light: "#8A6416",
    dark: "#F0CD7C",
  },
  success: {
    light: "#1C8753",
    dark: "#3FBE7D",
  },
  warning: {
    light: "#B7791F",
    dark: "#E3A73B",
  },
  danger: {
    light: "#B42318",
    dark: "#F0685C",
  },
  info: {
    light: "#0B6E8F",
    dark: "#4FC1E0",
  },
  background: {
    light: "#F7F8FA",
    dark: "#0B1220",
  },
  surface: {
    light: "#FFFFFF",
    dark: "#131B2C",
  },
  surfaceAlt: {
    light: "#EFF2F6",
    dark: "#1B2436",
  },
  border: {
    light: "#DEE3EA",
    dark: "#26314A",
  },
  text: {
    light: "#101828",
    dark: "#EEF1F6",
  },
  textMuted: {
    light: "#5A6472",
    dark: "#9AA6BA",
  },
  disabled: {
    light: "#CBD3DC",
    dark: "#333F58",
  },
  onPrimary: {
    light: "#FFFFFF",
    dark: "#101828",
  },
  onSecondary: {
    light: "#101828",
    dark: "#101828",
  },
  onDanger: {
    light: "#FFFFFF",
    dark: "#101828",
  },
  onSuccess: {
    light: "#FFFFFF",
    dark: "#101828",
  },
  onWarning: {
    light: "#101828",
    dark: "#101828",
  },
  onInfo: {
    light: "#FFFFFF",
    dark: "#101828",
  },
} as const;

export type ColorTokenName = keyof typeof ColorTokenValues;
